name: Mailing-List
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: echo install
      - name: Run Python
        run: python main.py "${{ secrets.SMTP_ID }}" "${{ secrets.SMTP_PW }}"
