name: Update Abstracts
on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 15 * * *'

jobs:
  get-papers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Scrape 
        env:
          OpenAI_API_KEY: ${{ secrets.OpenAI_API_KEY }}
        run: python main.py config.json "$OpenAI_API_KEY"
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "update abstract and html redirect"
          add: "."
