name: Update Abstracts
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  get-papers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Scrape Data
        run: echo scrape
      - name: Update html
        run: python update_html.py
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "update abstract and html redirect"
          add: "index.html"
